#!/usr/bin/env python3
"""Save an analysis generated by the OpenClaw agent into MongoDB.

Usage:
    python3 save_analysis.py --competitor-id <id> --change-ids <id1,id2> --analysis <json>

The agent calls this after it has analyzed changes. The analysis JSON should
match the AnalysisContent schema:
{
    "summary": "...",
    "impact_assessment": "...",
    "actionable_insights": ["...", "..."],
    "category": "pricing|product|tech_stack|partnership|content|other",
    "confidence": 0.87
}
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import db


def save_analysis(
    competitor_id: str,
    change_ids: list[str],
    analysis_content: dict,
    analysis_type: str = "change_analysis",
    raw_response: str = "",
) -> str:
    """Save analysis and mark associated changes as analyzed."""
    now = datetime.now(timezone.utc)
    doc = {
        "_id": str(__import__("bson").ObjectId()),
        "competitor_id": competitor_id,
        "change_ids": change_ids,
        "analysis_type": analysis_type,
        "generated_at": now,
        "content": analysis_content,
        "raw_response": raw_response,
        "created_at": now,
    }
    analysis_id = db.save_analysis(doc)

    # Mark each change as analyzed
    for change_id in change_ids:
        db.mark_change_analyzed(change_id, analysis_id)

    return analysis_id


def main():
    parser = argparse.ArgumentParser(description="Save agent analysis to MongoDB")
    parser.add_argument("--competitor-id", required=True, help="Competitor ID")
    parser.add_argument("--change-ids", required=True, help="Comma-separated change IDs")
    parser.add_argument("--analysis", required=True, help="Analysis JSON string")
    parser.add_argument("--type", default="change_analysis", help="Analysis type")
    parser.add_argument("--raw-response", default="", help="Full raw agent response")
    args = parser.parse_args()

    try:
        change_ids = [cid.strip() for cid in args.change_ids.split(",")]
        analysis_content = json.loads(args.analysis)

        analysis_id = save_analysis(
            competitor_id=args.competitor_id,
            change_ids=change_ids,
            analysis_content=analysis_content,
            analysis_type=args.type,
            raw_response=args.raw_response,
        )

        print(json.dumps({
            "status": "saved",
            "analysis_id": analysis_id,
            "changes_marked": len(change_ids),
        }, indent=2))

    except json.JSONDecodeError as e:
        print(json.dumps({"error": f"Invalid JSON: {e}"}), file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(json.dumps({"error": str(e)}), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
